// Mocks generated by Mockito 5.1.0 from annotations
// in africhange_screening/test/unit_test/currency_view_model_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i3;

import 'package:africhange_screening/data/models/currency_rate.dart' as _i4;
import 'package:africhange_screening/data/repository/currency_repository.dart'
    as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types

/// A class which mocks [CurrencyRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockCurrencyRepository extends _i1.Mock
    implements _i2.CurrencyRepository {
  MockCurrencyRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<List<_i4.CurrencyRate>> getLatestCurrencyRates() =>
      (super.noSuchMethod(Invocation.method(#getLatestCurrencyRates, []),
              returnValue:
                  Future<List<_i4.CurrencyRate>>.value(<_i4.CurrencyRate>[]))
          as _i3.Future<List<_i4.CurrencyRate>>);
  @override
  _i3.Future<List<num>> getPriceHistoricRange(List<String>? dateRange) => (super
          .noSuchMethod(Invocation.method(#getPriceHistoricRange, [dateRange]),
              returnValue: Future<List<num>>.value(<num>[]))
      as _i3.Future<List<num>>);
}
